apiVersion: v1
kind: Service
metadata:
  name: get-image-info-webapp
  labels:
    app: get-image-info
    role: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: "http-server"
  selector:
    app: get-image-info
    role: frontend

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: get-image-info-webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: get-image-info
        role: frontend
    spec:
      containers:
      - name: get-image-info-webapp
        image: gcr.io/$GCLOUD_PROJECT/get-image-info-webapp
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis-master
        - name: GCLOUD_PROJECT
          value: $GCLOUD_PROJECT
        ports:
        - name: http-server
          containerPort: 8080